# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_fulldbresult', '0005_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresultmeta',
            name='exchange',
            field=models.CharField(blank=True, default=None, max_length=191, null=True, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='taskresultmeta',
            name='hostname',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='taskresultmeta',
            name='routing_key',
            field=models.CharField(blank=True, default=None, max_length=191, null=True, verbose_name='routing key'),
        ),
        migrations.AlterField(
            model_name='taskresultmeta',
            name='task',
            field=models.CharField(max_length=191, verbose_name='task name'),
        ),
        migrations.AlterField(
            model_name='taskresultmeta',
            name='task_id',
            field=models.CharField(max_length=191, unique=True, verbose_name='task id'),
        ),
    ]
